### ISSUE TITLE
Compile errors with CLang7 & libc++

### ISSUE THREAD

**Issue by abrownsword** [CLIUtils/CLI11#158]
I updated to CLI v1.6.1 and started getting errors about the inclusion of <experimental/optional>, telling me <optional> should be included instead (this is because the <experimental/optional> header remains in place to generate an error that it shouldn't be used).  Examining Optional.hpp it is apparent that when compiling for C++17, _both_ CLI11_STD_OPTIONAL and CLI11_EXPERIMENTAL_OPTIONAL are defined and therefore both <optional> and <experimental/optional> are included.  Adding a !defined(CLI11_STD_OPTIONAL) to the #if around #define CLI11_EXPERIMENTAL_OPTIONAL fixes this.  A similar thing should be done with the boost optional.

**Comment by henryiii** [comment]
You are correct, fixing in coming PR. Are you sure it makes sense to drop boost optional if optional and boost are both available? They shouldn't clash, and a user may still want to use Boost.

**Comment by abrownsword** [comment]
I have no opinion on the boost support -- I don't use it and don't have it installed.  If you're sure they don't clash then leaving it enabled ought to be fine.

**Comment by henryiii** [comment]
It will only activate if you have Boost. You can always disable it by defining `CLI11_BOOST_OPTIONAL` as 0. You can also do this before CLI11 1.6.2 comes out with `CLI11_EXPERIMENTAL_OPTIONAL`, if defined to 0 it will not try to activate even if present.

**Comment by henryiii** [comment]
Please verify this is now fixed in master through #159.

**Comment by nyanpasu64** [comment]
I'm still getting an error. I think #159 is wrong, it should check `!defined(CLI11_STD_OPTIONAL) || CLI11_STD_OPTIONAL == 0`.

https://github.com/CLIUtils/CLI11/blob/4389b332ff03d09a074e2b2f685e9c9b90e48485/include/CLI/Optional.hpp#L22

Right now, it includes experimental only if non-experimental already exists!

------

Changing to `CLI11_STD_OPTIONAL == 0` fixes build for me.

**Comment by henryiii** [comment]
Check and see if that is better, please! Thanks.

**Comment by nyanpasu64** [comment]
i can't exactly check, considering I applied the patch directly on the release CLI11.hpp. But this is the same as the working code I have locally (Android Studio NDK r18 Beta 2).

**Comment by henryiii** [comment]
Okay, I'll assume for a 1 char fix that's safe enough. :)

**Comment by abrownsword** [comment]
Apologies, I haven't had time to sync and test this yet.

**Comment by abrownsword** [comment]
I have built from HEAD using Clang 7.0.0 on Linux and it worked perfectly.  Thanks.
